//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tvl.VisualStudio.Language.Java.JvmDebugSessionService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="JvmDebugSessionService.IJvmDebugSessionService")]
    public interface IJvmDebugSessionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmDebugSessionService/Attach", ReplyAction="http://tempuri.org/IJvmDebugSessionService/AttachResponse")]
        void Attach();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmDebugSessionService/Detach", ReplyAction="http://tempuri.org/IJvmDebugSessionService/DetachResponse")]
        void Detach();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmDebugSessionService/Terminate", ReplyAction="http://tempuri.org/IJvmDebugSessionService/TerminateResponse")]
        void Terminate();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IJvmDebugSessionServiceChannel : Tvl.VisualStudio.Language.Java.JvmDebugSessionService.IJvmDebugSessionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JvmDebugSessionServiceClient : System.ServiceModel.ClientBase<Tvl.VisualStudio.Language.Java.JvmDebugSessionService.IJvmDebugSessionService>, Tvl.VisualStudio.Language.Java.JvmDebugSessionService.IJvmDebugSessionService {
        
        public JvmDebugSessionServiceClient() {
        }
        
        public JvmDebugSessionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JvmDebugSessionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JvmDebugSessionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JvmDebugSessionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Attach() {
            base.Channel.Attach();
        }
        
        public void Detach() {
            base.Channel.Detach();
        }
        
        public void Terminate() {
            base.Channel.Terminate();
        }
    }
}
