//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tvl.VisualStudio.Language.Java.JvmToolsService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JvmVirtualMachineRemoteHandle", Namespace="http://schemas.datacontract.org/2004/07/Tvl.Java.DebugHost.Services")]
    [System.SerializableAttribute()]
    public partial struct JvmVirtualMachineRemoteHandle : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long HandleField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long Handle {
            get {
                return this.HandleField;
            }
            set {
                if ((this.HandleField.Equals(value) != true)) {
                    this.HandleField = value;
                    this.RaisePropertyChanged("Handle");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JvmThreadRemoteHandle", Namespace="http://schemas.datacontract.org/2004/07/Tvl.Java.DebugHost.Services")]
    [System.SerializableAttribute()]
    public partial struct JvmThreadRemoteHandle : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long HandleField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long Handle {
            get {
                return this.HandleField;
            }
            set {
                if ((this.HandleField.Equals(value) != true)) {
                    this.HandleField = value;
                    this.RaisePropertyChanged("Handle");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="jvmtiError", Namespace="http://schemas.datacontract.org/2004/07/Tvl.Java.DebugHost.Interop")]
    public enum jvmtiError : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NullPointer = 100,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OutOfMemory = 110,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccessDenied = 111,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnattachedThread = 115,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidEnvironment = 116,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WrongPhase = 112,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Internal = 113,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidPriority = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ThreadNotSuspended = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ThreadSuspended = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ThreadNotAlive = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ClassNotPrepared = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoMoreFrames = 31,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OpaqueFrame = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Duplicate = 40,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotFound = 41,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotMonitorOwner = 51,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Interrupt = 52,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnmodifiableClass = 79,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotAvailable = 98,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AbsentInformation = 101,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidEventType = 102,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NativeMethod = 104,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ClassLoaderUnsupported = 106,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidThread = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidFieldid = 25,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidMethodid = 23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidLocation = 24,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidObject = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidClass = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TypeMismatch = 34,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidSlot = 35,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MustPossessCapability = 99,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidThreadGroup = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidMonitor = 50,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IllegalArgument = 103,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidTypestate = 65,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnsupportedVersion = 68,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidClassFormat = 60,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CircularClassDefinition = 61,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnsupportedRedefinitionMethodAdded = 63,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnsupportedRedefinitionSchemaChanged = 64,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FailsVerification = 62,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnsupportedRedefinitionHierarchyChanged = 66,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnsupportedRedefinitionMethodDeleted = 67,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NamesDontMatch = 69,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnsupportedRedefinitionClassModifiersChanged = 70,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnsupportedRedefinitionMethodModifiersChanged = 71,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JvmRemoteLocation", Namespace="http://schemas.datacontract.org/2004/07/Tvl.Java.DebugHost.Services")]
    [System.SerializableAttribute()]
    public partial struct JvmRemoteLocation : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long MethodField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Location {
            get {
                return this.LocationField;
            }
            set {
                if ((this.LocationField.Equals(value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Method {
            get {
                return this.MethodField;
            }
            set {
                if ((this.MethodField.Equals(value) != true)) {
                    this.MethodField = value;
                    this.RaisePropertyChanged("Method");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JvmFieldRemoteHandle", Namespace="http://schemas.datacontract.org/2004/07/Tvl.Java.DebugHost.Services")]
    [System.SerializableAttribute()]
    public partial struct JvmFieldRemoteHandle : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Tvl.VisualStudio.Language.Java.JvmToolsService.JvmClassRemoteHandle ClassField;
        
        private long HandleField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Tvl.VisualStudio.Language.Java.JvmToolsService.JvmClassRemoteHandle Class {
            get {
                return this.ClassField;
            }
            set {
                if ((this.ClassField.Equals(value) != true)) {
                    this.ClassField = value;
                    this.RaisePropertyChanged("Class");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long Handle {
            get {
                return this.HandleField;
            }
            set {
                if ((this.HandleField.Equals(value) != true)) {
                    this.HandleField = value;
                    this.RaisePropertyChanged("Handle");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JvmClassRemoteHandle", Namespace="http://schemas.datacontract.org/2004/07/Tvl.Java.DebugHost.Services")]
    [System.SerializableAttribute()]
    public partial struct JvmClassRemoteHandle : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long HandleField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long Handle {
            get {
                return this.HandleField;
            }
            set {
                if ((this.HandleField.Equals(value) != true)) {
                    this.HandleField = value;
                    this.RaisePropertyChanged("Handle");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JvmObjectRemoteHandle", Namespace="http://schemas.datacontract.org/2004/07/Tvl.Java.DebugHost.Services")]
    [System.SerializableAttribute()]
    public partial struct JvmObjectRemoteHandle : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long HandleField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long Handle {
            get {
                return this.HandleField;
            }
            set {
                if ((this.HandleField.Equals(value) != true)) {
                    this.HandleField = value;
                    this.RaisePropertyChanged("Handle");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="jvmtiClassStatus", Namespace="http://schemas.datacontract.org/2004/07/Tvl.Java.DebugHost.Interop")]
    public enum jvmtiClassStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Verified = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Prepared = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Initialized = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Array = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Primitive = 32,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="JvmAccessModifiers", Namespace="http://schemas.datacontract.org/2004/07/Tvl.Java.DebugHost")]
    public enum JvmAccessModifiers : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Public = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Private = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Protected = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Static = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Final = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Super = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Synchronized = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Volatile = 64,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Transient = 128,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Native = 256,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Interface = 512,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Abstract = 1024,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Strict = 2048,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JvmMethodRemoteHandle", Namespace="http://schemas.datacontract.org/2004/07/Tvl.Java.DebugHost.Services")]
    [System.SerializableAttribute()]
    public partial struct JvmMethodRemoteHandle : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long HandleField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long Handle {
            get {
                return this.HandleField;
            }
            set {
                if ((this.HandleField.Equals(value) != true)) {
                    this.HandleField = value;
                    this.RaisePropertyChanged("Handle");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="jvmtiThreadState", Namespace="http://schemas.datacontract.org/2004/07/Tvl.Java.DebugHost.Interop")]
    public enum jvmtiThreadState : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Alive = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Terminated = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Runnable = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BlockedOnMonitorEnter = 1024,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Waiting = 128,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WaitingIndefinitely = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WaitingWithTimeout = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sleeping = 64,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InObjectWait = 256,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Parked = 512,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Suspended = 1048576,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Interrupted = 2097152,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InNative = 4194304,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Vendor1 = 268435456,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Vendor2 = 536870912,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Vendor3 = 1073741824,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JvmThreadRemoteInfo", Namespace="http://schemas.datacontract.org/2004/07/Tvl.Java.DebugHost.Services")]
    [System.SerializableAttribute()]
    public partial struct JvmThreadRemoteInfo : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Tvl.VisualStudio.Language.Java.JvmToolsService.JvmObjectRemoteHandle ContextClassLoaderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDaemonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PriorityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadGroupRemoteHandle ThreadGroupField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Tvl.VisualStudio.Language.Java.JvmToolsService.JvmObjectRemoteHandle ContextClassLoader {
            get {
                return this.ContextClassLoaderField;
            }
            set {
                if ((this.ContextClassLoaderField.Equals(value) != true)) {
                    this.ContextClassLoaderField = value;
                    this.RaisePropertyChanged("ContextClassLoader");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDaemon {
            get {
                return this.IsDaemonField;
            }
            set {
                if ((this.IsDaemonField.Equals(value) != true)) {
                    this.IsDaemonField = value;
                    this.RaisePropertyChanged("IsDaemon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Priority {
            get {
                return this.PriorityField;
            }
            set {
                if ((this.PriorityField.Equals(value) != true)) {
                    this.PriorityField = value;
                    this.RaisePropertyChanged("Priority");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadGroupRemoteHandle ThreadGroup {
            get {
                return this.ThreadGroupField;
            }
            set {
                if ((this.ThreadGroupField.Equals(value) != true)) {
                    this.ThreadGroupField = value;
                    this.RaisePropertyChanged("ThreadGroup");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JvmThreadGroupRemoteHandle", Namespace="http://schemas.datacontract.org/2004/07/Tvl.Java.DebugHost.Services")]
    [System.SerializableAttribute()]
    public partial struct JvmThreadGroupRemoteHandle : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long HandleField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long Handle {
            get {
                return this.HandleField;
            }
            set {
                if ((this.HandleField.Equals(value) != true)) {
                    this.HandleField = value;
                    this.RaisePropertyChanged("Handle");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JvmRemoteStackInfo", Namespace="http://schemas.datacontract.org/2004/07/Tvl.Java.DebugHost.Services")]
    [System.SerializableAttribute()]
    public partial struct JvmRemoteStackInfo : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="JvmToolsService.IJvmToolsInterfaceService")]
    public interface IJvmToolsInterfaceService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmToolsInterfaceService/SetLocalInt", ReplyAction="http://tempuri.org/IJvmToolsInterfaceService/SetLocalIntResponse")]
        Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError SetLocalInt(Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle thread, int depth, int slot, int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmToolsInterfaceService/SetLocalLong", ReplyAction="http://tempuri.org/IJvmToolsInterfaceService/SetLocalLongResponse")]
        Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError SetLocalLong(Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle thread, int depth, int slot, long value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmToolsInterfaceService/SetLocalFloat", ReplyAction="http://tempuri.org/IJvmToolsInterfaceService/SetLocalFloatResponse")]
        Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError SetLocalFloat(Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle thread, int depth, int slot, float value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmToolsInterfaceService/SetLocalDouble", ReplyAction="http://tempuri.org/IJvmToolsInterfaceService/SetLocalDoubleResponse")]
        Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError SetLocalDouble(Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle thread, int depth, int slot, double value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmToolsInterfaceService/SetBreakpoint", ReplyAction="http://tempuri.org/IJvmToolsInterfaceService/SetBreakpointResponse")]
        Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError SetBreakpoint(Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmRemoteLocation location);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmToolsInterfaceService/ClearBreakpoint", ReplyAction="http://tempuri.org/IJvmToolsInterfaceService/ClearBreakpointResponse")]
        Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError ClearBreakpoint(Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmRemoteLocation location);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmToolsInterfaceService/SetFieldAccessWatch", ReplyAction="http://tempuri.org/IJvmToolsInterfaceService/SetFieldAccessWatchResponse")]
        Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError SetFieldAccessWatch(Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmFieldRemoteHandle field);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmToolsInterfaceService/ClearFieldAccessWatch", ReplyAction="http://tempuri.org/IJvmToolsInterfaceService/ClearFieldAccessWatchResponse")]
        Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError ClearFieldAccessWatch(Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmFieldRemoteHandle field);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmToolsInterfaceService/SetFieldModificationWatch", ReplyAction="http://tempuri.org/IJvmToolsInterfaceService/SetFieldModificationWatchResponse")]
        Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError SetFieldModificationWatch(Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmFieldRemoteHandle field);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmToolsInterfaceService/ClearFieldModificationWatch", ReplyAction="http://tempuri.org/IJvmToolsInterfaceService/ClearFieldModificationWatchResponse")]
        Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError ClearFieldModificationWatch(Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmFieldRemoteHandle field);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmToolsInterfaceService/GetLoadedClasses", ReplyAction="http://tempuri.org/IJvmToolsInterfaceService/GetLoadedClassesResponse")]
        Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetLoadedClasses(out Tvl.VisualStudio.Language.Java.JvmToolsService.JvmClassRemoteHandle[] classes, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmToolsInterfaceService/GetClassLoaderClasses", ReplyAction="http://tempuri.org/IJvmToolsInterfaceService/GetClassLoaderClassesResponse")]
        Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetClassLoaderClasses(out Tvl.VisualStudio.Language.Java.JvmToolsService.JvmClassRemoteHandle[] classes, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmObjectRemoteHandle initiatingLoader);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmToolsInterfaceService/GetClassSignature", ReplyAction="http://tempuri.org/IJvmToolsInterfaceService/GetClassSignatureResponse")]
        Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetClassSignature(out string signature, out string generic, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmClassRemoteHandle @class);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmToolsInterfaceService/GetClassStatus", ReplyAction="http://tempuri.org/IJvmToolsInterfaceService/GetClassStatusResponse")]
        Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetClassStatus(out Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiClassStatus status, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmClassRemoteHandle @class);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmToolsInterfaceService/GetSourceFileName", ReplyAction="http://tempuri.org/IJvmToolsInterfaceService/GetSourceFileNameResponse")]
        Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetSourceFileName(out string sourceName, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmClassRemoteHandle @class);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmToolsInterfaceService/GetClassModifiers", ReplyAction="http://tempuri.org/IJvmToolsInterfaceService/GetClassModifiersResponse")]
        Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetClassModifiers(out Tvl.VisualStudio.Language.Java.JvmToolsService.JvmAccessModifiers modifiers, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmClassRemoteHandle @class);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmToolsInterfaceService/GetClassMethods", ReplyAction="http://tempuri.org/IJvmToolsInterfaceService/GetClassMethodsResponse")]
        Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetClassMethods(out Tvl.VisualStudio.Language.Java.JvmToolsService.JvmMethodRemoteHandle[] methods, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmClassRemoteHandle @class);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmToolsInterfaceService/GetClassFields", ReplyAction="http://tempuri.org/IJvmToolsInterfaceService/GetClassFieldsResponse")]
        Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetClassFields(out Tvl.VisualStudio.Language.Java.JvmToolsService.JvmFieldRemoteHandle[] fields, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmClassRemoteHandle @class);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmToolsInterfaceService/GetImplementedInterfaces", ReplyAction="http://tempuri.org/IJvmToolsInterfaceService/GetImplementedInterfacesResponse")]
        Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetImplementedInterfaces(out Tvl.VisualStudio.Language.Java.JvmToolsService.JvmClassRemoteHandle[] interfaces, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmClassRemoteHandle @class);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmToolsInterfaceService/GetClassVersionNumbers", ReplyAction="http://tempuri.org/IJvmToolsInterfaceService/GetClassVersionNumbersResponse")]
        Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetClassVersionNumbers(out int minorVersion, out int majorVersion, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmClassRemoteHandle @class);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmToolsInterfaceService/GetConstantPool", ReplyAction="http://tempuri.org/IJvmToolsInterfaceService/GetConstantPoolResponse")]
        Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetConstantPool(out byte[] constantPool, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmClassRemoteHandle @class);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmToolsInterfaceService/IsInterface", ReplyAction="http://tempuri.org/IJvmToolsInterfaceService/IsInterfaceResponse")]
        Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError IsInterface([System.ServiceModel.MessageParameterAttribute(Name="isInterface")] out bool isInterface1, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmClassRemoteHandle @class);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmToolsInterfaceService/IsArrayClass", ReplyAction="http://tempuri.org/IJvmToolsInterfaceService/IsArrayClassResponse")]
        Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError IsArrayClass([System.ServiceModel.MessageParameterAttribute(Name="isArrayClass")] out bool isArrayClass1, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmClassRemoteHandle @class);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmToolsInterfaceService/IsModifiableClass", ReplyAction="http://tempuri.org/IJvmToolsInterfaceService/IsModifiableClassResponse")]
        Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError IsModifiableClass([System.ServiceModel.MessageParameterAttribute(Name="isModifiableClass")] out bool isModifiableClass1, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmClassRemoteHandle @class);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmToolsInterfaceService/GetClassLoader", ReplyAction="http://tempuri.org/IJvmToolsInterfaceService/GetClassLoaderResponse")]
        Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetClassLoader(out Tvl.VisualStudio.Language.Java.JvmToolsService.JvmObjectRemoteHandle classLoader, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmClassRemoteHandle @class);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmToolsInterfaceService/GetSourceDebugExtension", ReplyAction="http://tempuri.org/IJvmToolsInterfaceService/GetSourceDebugExtensionResponse")]
        Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetSourceDebugExtension(out string sourceDebugExtension, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmClassRemoteHandle @class);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmToolsInterfaceService/RetransformClasses", ReplyAction="http://tempuri.org/IJvmToolsInterfaceService/RetransformClassesResponse")]
        Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError RetransformClasses(Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmClassRemoteHandle[] classes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmToolsInterfaceService/GetObjectSize", ReplyAction="http://tempuri.org/IJvmToolsInterfaceService/GetObjectSizeResponse")]
        Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetObjectSize(out long size, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmObjectRemoteHandle @object);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmToolsInterfaceService/GetObjectHashCode", ReplyAction="http://tempuri.org/IJvmToolsInterfaceService/GetObjectHashCodeResponse")]
        Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetObjectHashCode(out int hashCode, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmObjectRemoteHandle @object);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmToolsInterfaceService/Allocate", ReplyAction="http://tempuri.org/IJvmToolsInterfaceService/AllocateResponse")]
        Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError Allocate(out long address, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, long size);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmToolsInterfaceService/Deallocate", ReplyAction="http://tempuri.org/IJvmToolsInterfaceService/DeallocateResponse")]
        Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError Deallocate(Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, long address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmToolsInterfaceService/GetThreadState", ReplyAction="http://tempuri.org/IJvmToolsInterfaceService/GetThreadStateResponse")]
        Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetThreadState(out Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiThreadState threadState, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle thread);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmToolsInterfaceService/GetCurrentThread", ReplyAction="http://tempuri.org/IJvmToolsInterfaceService/GetCurrentThreadResponse")]
        Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetCurrentThread(out Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle thread, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmToolsInterfaceService/GetAllThreads", ReplyAction="http://tempuri.org/IJvmToolsInterfaceService/GetAllThreadsResponse")]
        Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetAllThreads(out Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle[] threads, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmToolsInterfaceService/SuspendThread", ReplyAction="http://tempuri.org/IJvmToolsInterfaceService/SuspendThreadResponse")]
        Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError SuspendThread(Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle thread);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmToolsInterfaceService/SuspendThreads", ReplyAction="http://tempuri.org/IJvmToolsInterfaceService/SuspendThreadsResponse")]
        Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError SuspendThreads(Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle[] threads);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmToolsInterfaceService/ResumeThread", ReplyAction="http://tempuri.org/IJvmToolsInterfaceService/ResumeThreadResponse")]
        Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError ResumeThread(Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle thread);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmToolsInterfaceService/ResumeThreads", ReplyAction="http://tempuri.org/IJvmToolsInterfaceService/ResumeThreadsResponse")]
        Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError ResumeThreads(Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle threads);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmToolsInterfaceService/StopThread", ReplyAction="http://tempuri.org/IJvmToolsInterfaceService/StopThreadResponse")]
        Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError StopThread(Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle thread, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmObjectRemoteHandle exception);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmToolsInterfaceService/InterruptThread", ReplyAction="http://tempuri.org/IJvmToolsInterfaceService/InterruptThreadResponse")]
        Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError InterruptThread(Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle thread);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmToolsInterfaceService/GetThreadInfo", ReplyAction="http://tempuri.org/IJvmToolsInterfaceService/GetThreadInfoResponse")]
        Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetThreadInfo(out Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteInfo info, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle thread);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmToolsInterfaceService/GetOwnedMonitorInfo", ReplyAction="http://tempuri.org/IJvmToolsInterfaceService/GetOwnedMonitorInfoResponse")]
        Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetOwnedMonitorInfo(out Tvl.VisualStudio.Language.Java.JvmToolsService.JvmObjectRemoteHandle[] ownedMonitors, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle thread);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmToolsInterfaceService/GetCurrentContendedMonitor", ReplyAction="http://tempuri.org/IJvmToolsInterfaceService/GetCurrentContendedMonitorResponse")]
        Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetCurrentContendedMonitor(out Tvl.VisualStudio.Language.Java.JvmToolsService.JvmObjectRemoteHandle monitor, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle thread);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmToolsInterfaceService/SetThreadLocalStorage", ReplyAction="http://tempuri.org/IJvmToolsInterfaceService/SetThreadLocalStorageResponse")]
        Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError SetThreadLocalStorage(Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle thread, long data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmToolsInterfaceService/GetThreadLocalStorage", ReplyAction="http://tempuri.org/IJvmToolsInterfaceService/GetThreadLocalStorageResponse")]
        Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetThreadLocalStorage(out long data, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle thread);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmToolsInterfaceService/GetTopThreadGroups", ReplyAction="http://tempuri.org/IJvmToolsInterfaceService/GetTopThreadGroupsResponse")]
        Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetTopThreadGroups(out Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadGroupRemoteHandle[] groups, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmToolsInterfaceService/GetThreadGroupChildren", ReplyAction="http://tempuri.org/IJvmToolsInterfaceService/GetThreadGroupChildrenResponse")]
        Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetThreadGroupChildren(out Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle[] threads, out Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadGroupRemoteHandle[] groups, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadGroupRemoteHandle group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmToolsInterfaceService/GetStackTrace", ReplyAction="http://tempuri.org/IJvmToolsInterfaceService/GetStackTraceResponse")]
        Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetStackTrace(out Tvl.VisualStudio.Language.Java.JvmToolsService.JvmRemoteLocation[] frames, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle thread, int startDepth, int maxFrameCount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmToolsInterfaceService/GetAllStackTraces", ReplyAction="http://tempuri.org/IJvmToolsInterfaceService/GetAllStackTracesResponse")]
        Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetAllStackTraces(out Tvl.VisualStudio.Language.Java.JvmToolsService.JvmRemoteStackInfo[] stackTraces, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, int maxFrameCount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmToolsInterfaceService/GetThreadListStackTraces", ReplyAction="http://tempuri.org/IJvmToolsInterfaceService/GetThreadListStackTracesResponse")]
        Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetThreadListStackTraces(out Tvl.VisualStudio.Language.Java.JvmToolsService.JvmRemoteStackInfo[] stackTraces, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle[] threads, int maxFrameCount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmToolsInterfaceService/GetFrameCount", ReplyAction="http://tempuri.org/IJvmToolsInterfaceService/GetFrameCountResponse")]
        Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetFrameCount(out int frameCount, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle thread);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmToolsInterfaceService/PopFrame", ReplyAction="http://tempuri.org/IJvmToolsInterfaceService/PopFrameResponse")]
        Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError PopFrame(Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle thread);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmToolsInterfaceService/GetFrameLocation", ReplyAction="http://tempuri.org/IJvmToolsInterfaceService/GetFrameLocationResponse")]
        Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetFrameLocation(out Tvl.VisualStudio.Language.Java.JvmToolsService.JvmRemoteLocation location, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle thread, int depth);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmToolsInterfaceService/NotifyFramePop", ReplyAction="http://tempuri.org/IJvmToolsInterfaceService/NotifyFramePopResponse")]
        Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError NotifyFramePop(Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle thread, int depth);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmToolsInterfaceService/ForceEarlyReturnObject", ReplyAction="http://tempuri.org/IJvmToolsInterfaceService/ForceEarlyReturnObjectResponse")]
        Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError ForceEarlyReturnObject(Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle thread, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmObjectRemoteHandle value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmToolsInterfaceService/ForceEarlyReturnInt", ReplyAction="http://tempuri.org/IJvmToolsInterfaceService/ForceEarlyReturnIntResponse")]
        Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError ForceEarlyReturnInt(Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle thread, int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmToolsInterfaceService/ForceEarlyReturnLong", ReplyAction="http://tempuri.org/IJvmToolsInterfaceService/ForceEarlyReturnLongResponse")]
        Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError ForceEarlyReturnLong(Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle thread, long value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmToolsInterfaceService/ForceEarlyReturnFloat", ReplyAction="http://tempuri.org/IJvmToolsInterfaceService/ForceEarlyReturnFloatResponse")]
        Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError ForceEarlyReturnFloat(Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle thread, float value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmToolsInterfaceService/ForceEarlyReturnDouble", ReplyAction="http://tempuri.org/IJvmToolsInterfaceService/ForceEarlyReturnDoubleResponse")]
        Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError ForceEarlyReturnDouble(Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle thread, double value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmToolsInterfaceService/ForceEarlyReturnVoid", ReplyAction="http://tempuri.org/IJvmToolsInterfaceService/ForceEarlyReturnVoidResponse")]
        Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError ForceEarlyReturnVoid(Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle thread);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmToolsInterfaceService/GetTag", ReplyAction="http://tempuri.org/IJvmToolsInterfaceService/GetTagResponse")]
        Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetTag(out long tag, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmObjectRemoteHandle @object);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmToolsInterfaceService/SetTag", ReplyAction="http://tempuri.org/IJvmToolsInterfaceService/SetTagResponse")]
        Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError SetTag(Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmObjectRemoteHandle @object, long tag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmToolsInterfaceService/GetObjectsWithTags", ReplyAction="http://tempuri.org/IJvmToolsInterfaceService/GetObjectsWithTagsResponse")]
        Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetObjectsWithTags(out Tvl.VisualStudio.Language.Java.JvmToolsService.JvmObjectRemoteHandle[] objects, out long[] tags, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, long[] tagFilter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmToolsInterfaceService/ForceGarbageCollection", ReplyAction="http://tempuri.org/IJvmToolsInterfaceService/ForceGarbageCollectionResponse")]
        Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError ForceGarbageCollection(Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmToolsInterfaceService/GetLocalObject", ReplyAction="http://tempuri.org/IJvmToolsInterfaceService/GetLocalObjectResponse")]
        Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetLocalObject(out Tvl.VisualStudio.Language.Java.JvmToolsService.JvmObjectRemoteHandle value, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle thread, int depth, int slot);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmToolsInterfaceService/GetLocalInstance", ReplyAction="http://tempuri.org/IJvmToolsInterfaceService/GetLocalInstanceResponse")]
        Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetLocalInstance(out Tvl.VisualStudio.Language.Java.JvmToolsService.JvmObjectRemoteHandle value, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle thread, int depth);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmToolsInterfaceService/GetLocalInt", ReplyAction="http://tempuri.org/IJvmToolsInterfaceService/GetLocalIntResponse")]
        Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetLocalInt(out int value, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle thread, int depth, int slot);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmToolsInterfaceService/GetLocalLong", ReplyAction="http://tempuri.org/IJvmToolsInterfaceService/GetLocalLongResponse")]
        Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetLocalLong(out long value, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle thread, int depth, int slot);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmToolsInterfaceService/GetLocalFloat", ReplyAction="http://tempuri.org/IJvmToolsInterfaceService/GetLocalFloatResponse")]
        Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetLocalFloat(out float value, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle thread, int depth, int slot);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmToolsInterfaceService/GetLocalDouble", ReplyAction="http://tempuri.org/IJvmToolsInterfaceService/GetLocalDoubleResponse")]
        Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetLocalDouble(out double value, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle thread, int depth, int slot);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJvmToolsInterfaceService/SetLocalObject", ReplyAction="http://tempuri.org/IJvmToolsInterfaceService/SetLocalObjectResponse")]
        Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError SetLocalObject(Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle thread, int depth, int slot, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmObjectRemoteHandle value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IJvmToolsInterfaceServiceChannel : Tvl.VisualStudio.Language.Java.JvmToolsService.IJvmToolsInterfaceService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JvmToolsInterfaceServiceClient : System.ServiceModel.ClientBase<Tvl.VisualStudio.Language.Java.JvmToolsService.IJvmToolsInterfaceService>, Tvl.VisualStudio.Language.Java.JvmToolsService.IJvmToolsInterfaceService {
        
        public JvmToolsInterfaceServiceClient() {
        }
        
        public JvmToolsInterfaceServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JvmToolsInterfaceServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JvmToolsInterfaceServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JvmToolsInterfaceServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError SetLocalInt(Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle thread, int depth, int slot, int value) {
            return base.Channel.SetLocalInt(virtualMachine, thread, depth, slot, value);
        }
        
        public Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError SetLocalLong(Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle thread, int depth, int slot, long value) {
            return base.Channel.SetLocalLong(virtualMachine, thread, depth, slot, value);
        }
        
        public Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError SetLocalFloat(Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle thread, int depth, int slot, float value) {
            return base.Channel.SetLocalFloat(virtualMachine, thread, depth, slot, value);
        }
        
        public Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError SetLocalDouble(Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle thread, int depth, int slot, double value) {
            return base.Channel.SetLocalDouble(virtualMachine, thread, depth, slot, value);
        }
        
        public Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError SetBreakpoint(Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmRemoteLocation location) {
            return base.Channel.SetBreakpoint(virtualMachine, location);
        }
        
        public Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError ClearBreakpoint(Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmRemoteLocation location) {
            return base.Channel.ClearBreakpoint(virtualMachine, location);
        }
        
        public Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError SetFieldAccessWatch(Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmFieldRemoteHandle field) {
            return base.Channel.SetFieldAccessWatch(virtualMachine, field);
        }
        
        public Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError ClearFieldAccessWatch(Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmFieldRemoteHandle field) {
            return base.Channel.ClearFieldAccessWatch(virtualMachine, field);
        }
        
        public Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError SetFieldModificationWatch(Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmFieldRemoteHandle field) {
            return base.Channel.SetFieldModificationWatch(virtualMachine, field);
        }
        
        public Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError ClearFieldModificationWatch(Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmFieldRemoteHandle field) {
            return base.Channel.ClearFieldModificationWatch(virtualMachine, field);
        }
        
        public Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetLoadedClasses(out Tvl.VisualStudio.Language.Java.JvmToolsService.JvmClassRemoteHandle[] classes, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine) {
            return base.Channel.GetLoadedClasses(out classes, virtualMachine);
        }
        
        public Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetClassLoaderClasses(out Tvl.VisualStudio.Language.Java.JvmToolsService.JvmClassRemoteHandle[] classes, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmObjectRemoteHandle initiatingLoader) {
            return base.Channel.GetClassLoaderClasses(out classes, virtualMachine, initiatingLoader);
        }
        
        public Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetClassSignature(out string signature, out string generic, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmClassRemoteHandle @class) {
            return base.Channel.GetClassSignature(out signature, out generic, virtualMachine, @class);
        }
        
        public Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetClassStatus(out Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiClassStatus status, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmClassRemoteHandle @class) {
            return base.Channel.GetClassStatus(out status, virtualMachine, @class);
        }
        
        public Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetSourceFileName(out string sourceName, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmClassRemoteHandle @class) {
            return base.Channel.GetSourceFileName(out sourceName, virtualMachine, @class);
        }
        
        public Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetClassModifiers(out Tvl.VisualStudio.Language.Java.JvmToolsService.JvmAccessModifiers modifiers, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmClassRemoteHandle @class) {
            return base.Channel.GetClassModifiers(out modifiers, virtualMachine, @class);
        }
        
        public Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetClassMethods(out Tvl.VisualStudio.Language.Java.JvmToolsService.JvmMethodRemoteHandle[] methods, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmClassRemoteHandle @class) {
            return base.Channel.GetClassMethods(out methods, virtualMachine, @class);
        }
        
        public Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetClassFields(out Tvl.VisualStudio.Language.Java.JvmToolsService.JvmFieldRemoteHandle[] fields, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmClassRemoteHandle @class) {
            return base.Channel.GetClassFields(out fields, virtualMachine, @class);
        }
        
        public Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetImplementedInterfaces(out Tvl.VisualStudio.Language.Java.JvmToolsService.JvmClassRemoteHandle[] interfaces, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmClassRemoteHandle @class) {
            return base.Channel.GetImplementedInterfaces(out interfaces, virtualMachine, @class);
        }
        
        public Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetClassVersionNumbers(out int minorVersion, out int majorVersion, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmClassRemoteHandle @class) {
            return base.Channel.GetClassVersionNumbers(out minorVersion, out majorVersion, virtualMachine, @class);
        }
        
        public Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetConstantPool(out byte[] constantPool, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmClassRemoteHandle @class) {
            return base.Channel.GetConstantPool(out constantPool, virtualMachine, @class);
        }
        
        public Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError IsInterface(out bool isInterface1, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmClassRemoteHandle @class) {
            return base.Channel.IsInterface(out isInterface1, virtualMachine, @class);
        }
        
        public Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError IsArrayClass(out bool isArrayClass1, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmClassRemoteHandle @class) {
            return base.Channel.IsArrayClass(out isArrayClass1, virtualMachine, @class);
        }
        
        public Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError IsModifiableClass(out bool isModifiableClass1, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmClassRemoteHandle @class) {
            return base.Channel.IsModifiableClass(out isModifiableClass1, virtualMachine, @class);
        }
        
        public Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetClassLoader(out Tvl.VisualStudio.Language.Java.JvmToolsService.JvmObjectRemoteHandle classLoader, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmClassRemoteHandle @class) {
            return base.Channel.GetClassLoader(out classLoader, virtualMachine, @class);
        }
        
        public Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetSourceDebugExtension(out string sourceDebugExtension, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmClassRemoteHandle @class) {
            return base.Channel.GetSourceDebugExtension(out sourceDebugExtension, virtualMachine, @class);
        }
        
        public Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError RetransformClasses(Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmClassRemoteHandle[] classes) {
            return base.Channel.RetransformClasses(virtualMachine, classes);
        }
        
        public Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetObjectSize(out long size, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmObjectRemoteHandle @object) {
            return base.Channel.GetObjectSize(out size, virtualMachine, @object);
        }
        
        public Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetObjectHashCode(out int hashCode, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmObjectRemoteHandle @object) {
            return base.Channel.GetObjectHashCode(out hashCode, virtualMachine, @object);
        }
        
        public Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError Allocate(out long address, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, long size) {
            return base.Channel.Allocate(out address, virtualMachine, size);
        }
        
        public Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError Deallocate(Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, long address) {
            return base.Channel.Deallocate(virtualMachine, address);
        }
        
        public Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetThreadState(out Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiThreadState threadState, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle thread) {
            return base.Channel.GetThreadState(out threadState, virtualMachine, thread);
        }
        
        public Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetCurrentThread(out Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle thread, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine) {
            return base.Channel.GetCurrentThread(out thread, virtualMachine);
        }
        
        public Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetAllThreads(out Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle[] threads, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine) {
            return base.Channel.GetAllThreads(out threads, virtualMachine);
        }
        
        public Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError SuspendThread(Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle thread) {
            return base.Channel.SuspendThread(virtualMachine, thread);
        }
        
        public Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError SuspendThreads(Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle[] threads) {
            return base.Channel.SuspendThreads(virtualMachine, threads);
        }
        
        public Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError ResumeThread(Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle thread) {
            return base.Channel.ResumeThread(virtualMachine, thread);
        }
        
        public Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError ResumeThreads(Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle threads) {
            return base.Channel.ResumeThreads(virtualMachine, threads);
        }
        
        public Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError StopThread(Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle thread, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmObjectRemoteHandle exception) {
            return base.Channel.StopThread(virtualMachine, thread, exception);
        }
        
        public Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError InterruptThread(Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle thread) {
            return base.Channel.InterruptThread(virtualMachine, thread);
        }
        
        public Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetThreadInfo(out Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteInfo info, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle thread) {
            return base.Channel.GetThreadInfo(out info, virtualMachine, thread);
        }
        
        public Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetOwnedMonitorInfo(out Tvl.VisualStudio.Language.Java.JvmToolsService.JvmObjectRemoteHandle[] ownedMonitors, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle thread) {
            return base.Channel.GetOwnedMonitorInfo(out ownedMonitors, virtualMachine, thread);
        }
        
        public Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetCurrentContendedMonitor(out Tvl.VisualStudio.Language.Java.JvmToolsService.JvmObjectRemoteHandle monitor, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle thread) {
            return base.Channel.GetCurrentContendedMonitor(out monitor, virtualMachine, thread);
        }
        
        public Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError SetThreadLocalStorage(Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle thread, long data) {
            return base.Channel.SetThreadLocalStorage(virtualMachine, thread, data);
        }
        
        public Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetThreadLocalStorage(out long data, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle thread) {
            return base.Channel.GetThreadLocalStorage(out data, virtualMachine, thread);
        }
        
        public Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetTopThreadGroups(out Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadGroupRemoteHandle[] groups, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine) {
            return base.Channel.GetTopThreadGroups(out groups, virtualMachine);
        }
        
        public Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetThreadGroupChildren(out Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle[] threads, out Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadGroupRemoteHandle[] groups, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadGroupRemoteHandle group) {
            return base.Channel.GetThreadGroupChildren(out threads, out groups, virtualMachine, group);
        }
        
        public Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetStackTrace(out Tvl.VisualStudio.Language.Java.JvmToolsService.JvmRemoteLocation[] frames, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle thread, int startDepth, int maxFrameCount) {
            return base.Channel.GetStackTrace(out frames, virtualMachine, thread, startDepth, maxFrameCount);
        }
        
        public Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetAllStackTraces(out Tvl.VisualStudio.Language.Java.JvmToolsService.JvmRemoteStackInfo[] stackTraces, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, int maxFrameCount) {
            return base.Channel.GetAllStackTraces(out stackTraces, virtualMachine, maxFrameCount);
        }
        
        public Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetThreadListStackTraces(out Tvl.VisualStudio.Language.Java.JvmToolsService.JvmRemoteStackInfo[] stackTraces, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle[] threads, int maxFrameCount) {
            return base.Channel.GetThreadListStackTraces(out stackTraces, virtualMachine, threads, maxFrameCount);
        }
        
        public Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetFrameCount(out int frameCount, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle thread) {
            return base.Channel.GetFrameCount(out frameCount, virtualMachine, thread);
        }
        
        public Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError PopFrame(Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle thread) {
            return base.Channel.PopFrame(virtualMachine, thread);
        }
        
        public Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetFrameLocation(out Tvl.VisualStudio.Language.Java.JvmToolsService.JvmRemoteLocation location, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle thread, int depth) {
            return base.Channel.GetFrameLocation(out location, virtualMachine, thread, depth);
        }
        
        public Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError NotifyFramePop(Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle thread, int depth) {
            return base.Channel.NotifyFramePop(virtualMachine, thread, depth);
        }
        
        public Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError ForceEarlyReturnObject(Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle thread, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmObjectRemoteHandle value) {
            return base.Channel.ForceEarlyReturnObject(virtualMachine, thread, value);
        }
        
        public Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError ForceEarlyReturnInt(Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle thread, int value) {
            return base.Channel.ForceEarlyReturnInt(virtualMachine, thread, value);
        }
        
        public Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError ForceEarlyReturnLong(Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle thread, long value) {
            return base.Channel.ForceEarlyReturnLong(virtualMachine, thread, value);
        }
        
        public Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError ForceEarlyReturnFloat(Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle thread, float value) {
            return base.Channel.ForceEarlyReturnFloat(virtualMachine, thread, value);
        }
        
        public Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError ForceEarlyReturnDouble(Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle thread, double value) {
            return base.Channel.ForceEarlyReturnDouble(virtualMachine, thread, value);
        }
        
        public Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError ForceEarlyReturnVoid(Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle thread) {
            return base.Channel.ForceEarlyReturnVoid(virtualMachine, thread);
        }
        
        public Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetTag(out long tag, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmObjectRemoteHandle @object) {
            return base.Channel.GetTag(out tag, virtualMachine, @object);
        }
        
        public Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError SetTag(Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmObjectRemoteHandle @object, long tag) {
            return base.Channel.SetTag(virtualMachine, @object, tag);
        }
        
        public Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetObjectsWithTags(out Tvl.VisualStudio.Language.Java.JvmToolsService.JvmObjectRemoteHandle[] objects, out long[] tags, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, long[] tagFilter) {
            return base.Channel.GetObjectsWithTags(out objects, out tags, virtualMachine, tagFilter);
        }
        
        public Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError ForceGarbageCollection(Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine) {
            return base.Channel.ForceGarbageCollection(virtualMachine);
        }
        
        public Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetLocalObject(out Tvl.VisualStudio.Language.Java.JvmToolsService.JvmObjectRemoteHandle value, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle thread, int depth, int slot) {
            return base.Channel.GetLocalObject(out value, virtualMachine, thread, depth, slot);
        }
        
        public Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetLocalInstance(out Tvl.VisualStudio.Language.Java.JvmToolsService.JvmObjectRemoteHandle value, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle thread, int depth) {
            return base.Channel.GetLocalInstance(out value, virtualMachine, thread, depth);
        }
        
        public Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetLocalInt(out int value, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle thread, int depth, int slot) {
            return base.Channel.GetLocalInt(out value, virtualMachine, thread, depth, slot);
        }
        
        public Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetLocalLong(out long value, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle thread, int depth, int slot) {
            return base.Channel.GetLocalLong(out value, virtualMachine, thread, depth, slot);
        }
        
        public Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetLocalFloat(out float value, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle thread, int depth, int slot) {
            return base.Channel.GetLocalFloat(out value, virtualMachine, thread, depth, slot);
        }
        
        public Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError GetLocalDouble(out double value, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle thread, int depth, int slot) {
            return base.Channel.GetLocalDouble(out value, virtualMachine, thread, depth, slot);
        }
        
        public Tvl.VisualStudio.Language.Java.JvmToolsService.jvmtiError SetLocalObject(Tvl.VisualStudio.Language.Java.JvmToolsService.JvmVirtualMachineRemoteHandle virtualMachine, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmThreadRemoteHandle thread, int depth, int slot, Tvl.VisualStudio.Language.Java.JvmToolsService.JvmObjectRemoteHandle value) {
            return base.Channel.SetLocalObject(virtualMachine, thread, depth, slot, value);
        }
    }
}
